### PR TITLE
Define evaluator Swagger spec

### PR DESCRIPTION
**Pull request by bruth**
See #1 

Signed-off-by: Byron Ruth b@devel.io

### CODE REVIEW

**Comment by bruth** [comment]
@harvest-platform/core Please review the initial draft. It may be easier to paste the contents of the file into the [live editor](http://editor.swagger.io/#/).

**Comment by bruth** [comment]
@gerpsh I did two minor things. Concepts parameters and operators are now array with an `id` field which was the key of the map before.

**Comment by bruth** [comment]
Please critique the heck out of it. Tell me there should be descriptions for everything, fix grammar, etc.

**Comment by bruth** [comment]
Also, I am a bit uneasy about the `/catalog` endpoint since it feels like duplicated functionality for what the concept registry should provide. The idea being, each evaluator would have a local concept registry (just like the Harvest system itself) and it would be a matter of registries talking to one another, rather than adding that requirement to evaluator since it is unrelated.

This provides two advantages, the evaluator can simply point to registry which contains the concepts it supports. More importantly, the registry is a self-contained managed service of the concepts whereas, right now, the concepts are being generated on the fly from the source database. For example, Harvest 2 concepts or ES document paths. The only time when the evaluator will have to synchronize its state is when the underlying concepts change, but that should be rare.

**Comment by bruth** [comment]
@gerpsh A few other things I changed:
- The output from the `/catalog` endpoint now encodes params and operators as arrays rather than an object. This prevents requiring the client to have to add the `id` of those elements back into the object.
- Likewise, a query will provide params as an array with the `id` in the object rather than as the object key.
- The mapped query now only includes the mapped ids and does not include the local ones. I've updated the [the gist](https://gist.github.com/bruth/4e44460ef4f5e84d6f58fdf85d1aa7f7) to show this. For example, the concept with name `audiogram.puretone.f500` is mapped to `331` and does not retain the local name. This is simply because there is no reason to provide that information. This mapping will be logged during the mapping phase, so we would not lose any information while the query is being traced.

One other change I would like to suggest is to use `"type": "concept"` for concept-based terms and change the `concept` key to `id`. For example, this:

``` json
{
  "type": "leaf",
  "concept": "audiogram.puretone.f500",
  "params": [ ]
}
```

to this

``` json
{
  "type": "concept",
  "id": "audiogram.puretone.f500",
  "params": [ ]
}
```

**Comment by gerpsh** [comment]
Excellent, thanks for defining these.  Agreed on changing "leaf" to "concept", leaf is too literal.  

Checking: `/plan` will output a client query (as opposed to a mapped query), correct?

In regards to the catalog, even though it's a fringe piece of functionality I still like the idea of it; in the case that a data source changes and in turn its evaluator supports a different set of concepts, the concept registry could hit the `/catalog` endpoint to check the changes.  I have a feeling you were thinking of some other mechanism to do this, so let me know if this is the case.

So just to verify how this will work, the query flow will go like this: client sends request -> coordinator works with concept registry to translate this into a mapped query, if necessary -> this mapped query is sent to an evaluator -> the evaluator works with the concept registry to translate this into a client query -> query is evaluated, etc.

**Comment by gerpsh** [comment]
@bruth Also, how do you see the data service fitting in here? I'd have thought that `/count` would be more on the data retrieval end of things than evaluation.

**Comment by bruth** [comment]
> `/plan` will out put a client query?

It takes a mapped query and output a representation of the internal query plan. i.e. the internal query it gets translated into. In your case the Elasticsearch query. The expectation of this endpoint is still not well-defined, but it is helpful to think through this because I believe it to be a necessary for debugging and/or monitoring.

> I have a feeling you were thinking of some other mechanism to do this, so let me know if this is the case.

You are correct about the changes. The solution would be that the evaluator is responsible for updating its local concept registry with the changes. This enable building a simple sync mechanism between registries rather than other other services needing to implement that. I will make a diagram for this.

> [...] the evaluator works with the concept registry to translate this into a client query -> query is evaluated, etc.

If by client query you mean the internal query like SQL or ES, then yes. But we should consider that an implementation detail. As long as evaluator can interpret the query given to it (mapped from another one in this case), then it works. The `/plan` endpoint was intended expose some of the internal planning for debugging.

> Also, how do you see the data service fitting in here? I'd have thought that `/count` would be more on the data retrieval end of things than evaluation.

Maybe not the data service since this is an aggregate value, but I agree it doesn't feel quite right. My logic was that it would be a shorthand and possibly more optimal path for computing a count rather than returning the `/idents` and then counting them locally. But it may be worth starting with only the `/idents` and seeing how far we can get. We should test it on a large data set.

**Comment by bruth** [comment]
This is more or less what I was thinking.

evaluator-init

**Comment by bruth** [comment]
Updated the image, it was not complete.

**Pull request closed without merging**
